### ISSUE TITLE
Plugin is not implemented on android or app crashes

### ISSUE THREAD

**Issue by Martijn0405** [RevenueCat/purchases-capacitor#120]
I am using this code on a NextJS project:
import { Purchases } from "@revenuecat/purchases-capacitor"

await Purchases.configure({
      apiKey,
      appUserID: uid
})

But getting this error:
Error: "CapacitorPurchases" plugin is not implemented on android

Does anyone maybe have any idea why it is not using Purchases instead of CapacitorPurchases?

When using:
import { CapacitorPurchases } from '@capgo/capacitor-purchases';

CapacitorPurchases.setDebugLogsEnabled({ enabled: true }).then()

The app crashes instrantly, what would be a correct and functioning code solution at this moment?

**Comment by danny-hunt** [comment]
To set up debug logging specifically, your code should include something like this:
```
import { Purchases } from "@revenuecat/purchases-capacitor"

Purchases.setLogLevel({ level: LOG_LEVEL.DEBUG });
```
More details in the migration guide

**Comment by Martijn0405** [comment]
> To set up debug logging specifically, your code should include something like this:
> 
> ```
> import { Purchases } from "@revenuecat/purchases-capacitor"
> 
> Purchases.setLogLevel({ level: LOG_LEVEL.DEBUG });
> ```
> 
> More details in the migration guide

Hi, I did use this code, but the error mentioned above appeared:
Error: "CapacitorPurchases" plugin is not implemented on android

I was not using the capgo module at that time.
import { CapacitorPurchases } from '@capgo/capacitor-purchases';

**Comment by tonidero** [comment]
Hi @Martijn0405, sorry for the delay.

As @danny-hunt said, you shouldn't be using `@capgo/capacitor-purchases` since that's deprecated. That also means that you shouldn't have any reference in your code to `CapacitorPurchases` since the plugin has been renamed to `Purchases`. Could you check to confirm this is the case? If you installed the previous versions of this plugin, you might have some leftovers.

**Comment by Martijn0405** [comment]
Hi, I have reinstalled node modules making sure the package @capgo/capacitor-purchases is not installed. However, when building and running the app for the first time it works and loads projects, but the second time it still has the error.

Uncaught (in promise) Error: "CapacitorPurchases" plugin is not implemented on android

Upon running: Purchases.getProducts(). I have no idea where is might be coming from.

**Comment by tonidero** [comment]
@Martijn0405 that is indeed weird, since "CapacitorPurchases" is how the plugin was called when the package was `@capgo/capacitor-purchases`. It was renamed to `Purchases` after moving to `@revenuecat/purchases-capacitor`... 

A few questions:
- Do you have any reference to `CapacitorPurchases` in your code? 
- Does this happen upon calling any other method in the plugin? 
- Also, could you share logs for when this happens, in case it may help us?

**Comment by Martijn0405** [comment]
- There is no other references of CapacitorPurchases, I also made sure to not install or use the @capgo/capacitor-purchases package
- I first run Purchases.configure and directly after Purchases.getProducts. Either one or both of these calls throws the error.
- The error in chrome devtools:
![Screenshot 2023-10-07 231012](https://github.com/RevenueCat/purchases-capacitor/assets/43009057/ab1a2d9e-3eec-4183-a016-717e6ae56478)

**Comment by tonidero** [comment]
Hmm could you try to clear your `node_modules` and any generated file from your code? I'm still unsure where that reference to `CapacitorPurchases` comes from, since it's not part of the plugin codebase anymore 🤔
